name: display_brightness_example
description: "Demonstrates how to use the display_brightness package."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.0

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  display_brightness:
    path: ../
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
