// AUTO GENERATED BY JNIGEN 0.16.0. DO NOT EDIT!

// ignore_for_file: annotate_overrides
// ignore_for_file: argument_type_not_assignable
// ignore_for_file: camel_case_extensions
// ignore_for_file: camel_case_types
// ignore_for_file: constant_identifier_names
// ignore_for_file: comment_references
// ignore_for_file: doc_directive_unknown
// ignore_for_file: file_names
// ignore_for_file: inference_failure_on_untyped_parameter
// ignore_for_file: invalid_internal_annotation
// ignore_for_file: invalid_use_of_internal_member
// ignore_for_file: library_prefixes
// ignore_for_file: lines_longer_than_80_chars
// ignore_for_file: no_leading_underscores_for_library_prefixes
// ignore_for_file: no_leading_underscores_for_local_identifiers
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: only_throw_errors
// ignore_for_file: overridden_fields
// ignore_for_file: prefer_double_quotes
// ignore_for_file: unintended_html_in_doc_comment
// ignore_for_file: unnecessary_cast
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: unused_element
// ignore_for_file: unused_field
// ignore_for_file: unused_import
// ignore_for_file: unused_local_variable
// ignore_for_file: unused_shown_name
// ignore_for_file: use_super_parameters

import 'dart:core' as core$_;
import 'dart:core' show Object, String;

import 'package:jni/_internal.dart' as jni$_;
import 'package:jni/jni.dart' as jni$_;

const _$jniVersionCheck = jni$_.JniVersionCheck(1, 0);

/// from: `fi.mankelisolutions.display_brightness.BrightnessCallback`
extension type BrightnessCallback._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'fi/mankelisolutions/display_brightness/BrightnessCallback',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<BrightnessCallback> type =
      $BrightnessCallback$Type$();

  /// Maps a specific port to the implemented interface.
  static final core$_.Map<core$_.int, $BrightnessCallback> _$impls = {};
  static jni$_.JObjectPtr _$invoke(
    core$_.int port,
    jni$_.JObjectPtr descriptor,
    jni$_.JObjectPtr args,
  ) {
    return _$invokeMethod(
      port,
      jni$_.MethodInvocation.fromAddresses(0, descriptor.address, args.address),
    );
  }

  static final jni$_.Pointer<
    jni$_.NativeFunction<
      jni$_.JObjectPtr Function(jni$_.Int64, jni$_.JObjectPtr, jni$_.JObjectPtr)
    >
  >
  _$invokePointer = jni$_.Pointer.fromFunction(_$invoke);

  static jni$_.Pointer<jni$_.Void> _$invokeMethod(
    core$_.int $p,
    jni$_.MethodInvocation $i,
  ) {
    try {
      final $d = $i.methodDescriptor.toDartString(releaseOriginal: true);
      final $a = $i.args;
      if ($d == r'onBrightnessChanged(D)V') {
        _$impls[$p]!.onBrightnessChanged(
          ($a![0] as jni$_.JDouble).toDartDouble(releaseOriginal: true),
        );
        return jni$_.nullptr;
      }
    } catch (e) {
      return jni$_.ProtectedJniExtensions.newDartException(e);
    }
    return jni$_.nullptr;
  }

  static void implementIn(
    jni$_.JImplementer implementer,
    $BrightnessCallback $impl,
  ) {
    late final jni$_.RawReceivePort $p;
    $p = jni$_.RawReceivePort(($m) {
      if ($m == null) {
        _$impls.remove($p.sendPort.nativePort);
        $p.close();
        return;
      }
      final $i = jni$_.MethodInvocation.fromMessage($m);
      final $r = _$invokeMethod($p.sendPort.nativePort, $i);
      jni$_.ProtectedJniExtensions.returnResult($i.result, $r);
    });
    implementer.add(
      r'fi.mankelisolutions.display_brightness.BrightnessCallback',
      $p,
      _$invokePointer,
      [if ($impl.onBrightnessChanged$async) r'onBrightnessChanged(D)V'],
    );
    final $a = $p.sendPort.nativePort;
    _$impls[$a] = $impl;
  }

  factory BrightnessCallback.implement($BrightnessCallback $impl) {
    final $i = jni$_.JImplementer();
    implementIn($i, $impl);
    return $i.implement<BrightnessCallback>();
  }
}

extension BrightnessCallback$$Methods on BrightnessCallback {
  static final _id_onBrightnessChanged = BrightnessCallback._class
      .instanceMethodId(r'onBrightnessChanged', r'(D)V');

  static final _onBrightnessChanged =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Double,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.double,
            )
          >();

  /// from: `public fun onBrightnessChanged(brightness: kotlin.Double): kotlin.Unit`
  void onBrightnessChanged(core$_.double d) {
    _onBrightnessChanged(
      reference.pointer,
      _id_onBrightnessChanged.pointer,
      d,
    ).check();
  }
}

abstract base mixin class $BrightnessCallback {
  factory $BrightnessCallback({
    required void Function(core$_.double d) onBrightnessChanged,
    core$_.bool onBrightnessChanged$async,
  }) = _$BrightnessCallback;

  void onBrightnessChanged(core$_.double d);
  core$_.bool get onBrightnessChanged$async => false;
}

final class _$BrightnessCallback with $BrightnessCallback {
  _$BrightnessCallback({
    required void Function(core$_.double d) onBrightnessChanged,
    this.onBrightnessChanged$async = false,
  }) : _onBrightnessChanged = onBrightnessChanged;

  final void Function(core$_.double d) _onBrightnessChanged;
  final core$_.bool onBrightnessChanged$async;

  void onBrightnessChanged(core$_.double d) {
    return _onBrightnessChanged(d);
  }
}

final class $BrightnessCallback$Type$ extends jni$_.JType<BrightnessCallback> {
  @jni$_.internal
  const $BrightnessCallback$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lfi/mankelisolutions/display_brightness/BrightnessCallback;';
}

/// from: `fi.mankelisolutions.display_brightness.DisplayBrightness`
extension type DisplayBrightness._(jni$_.JObject _$this)
    implements jni$_.JObject {
  static final _class = jni$_.JClass.forName(
    r'fi/mankelisolutions/display_brightness/DisplayBrightness',
  );

  /// The type which includes information such as the signature of this class.
  static const jni$_.JType<DisplayBrightness> type = $DisplayBrightness$Type$();
  static final _id_new$ = _class.constructorId(r'(Landroid/app/Activity;)V');

  static final _new$ =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_NewObject')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public void <init>(android.app.Activity activity)`
  /// The returned object must be released after use, by calling the [release] method.
  factory DisplayBrightness(jni$_.JObject activity) {
    final _$activity = activity.reference;
    return _new$(
      _class.reference.pointer,
      _id_new$.pointer,
      _$activity.pointer,
    ).object<DisplayBrightness>();
  }
}

extension DisplayBrightness$$Methods on DisplayBrightness {
  static final _id_get$brightness = DisplayBrightness._class.instanceMethodId(
    r'getBrightness',
    r'()Ljava/lang/Double;',
  );

  static final _get$brightness =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JniResult Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallObjectMethod')
          .asFunction<
            jni$_.JniResult Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public final java.lang.Double getBrightness()`
  /// The returned object must be released after use, by calling the [release] method.
  jni$_.JDouble? get brightness {
    return _get$brightness(
      reference.pointer,
      _id_get$brightness.pointer,
    ).object<jni$_.JDouble?>();
  }

  static final _id_set$brightness$1 = DisplayBrightness._class.instanceMethodId(
    r'setBrightness',
    r'(D)V',
  );

  static final _set$brightness$1 =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Double,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              core$_.double,
            )
          >();

  /// from: `public fun setBrightness(brightness: kotlin.Double): kotlin.Unit`
  set brightness$1(core$_.double d) {
    _set$brightness$1(
      reference.pointer,
      _id_set$brightness$1.pointer,
      d,
    ).check();
  }

  static final _id_startObserving = DisplayBrightness._class.instanceMethodId(
    r'startObserving',
    r'(Lfi/mankelisolutions/display_brightness/BrightnessCallback;)V',
  );

  static final _startObserving =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
                jni$_.VarArgs<(jni$_.Pointer<jni$_.Void>,)>,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
              jni$_.Pointer<jni$_.Void>,
            )
          >();

  /// from: `public fun startObserving(callback: fi.mankelisolutions.display_brightness.BrightnessCallback): kotlin.Unit`
  void startObserving(BrightnessCallback brightnessCallback) {
    final _$brightnessCallback = brightnessCallback.reference;
    _startObserving(
      reference.pointer,
      _id_startObserving.pointer,
      _$brightnessCallback.pointer,
    ).check();
  }

  static final _id_stopObserving = DisplayBrightness._class.instanceMethodId(
    r'stopObserving',
    r'()V',
  );

  static final _stopObserving =
      jni$_.ProtectedJniExtensions.lookup<
            jni$_.NativeFunction<
              jni$_.JThrowablePtr Function(
                jni$_.Pointer<jni$_.Void>,
                jni$_.JMethodIDPtr,
              )
            >
          >('globalEnv_CallVoidMethod')
          .asFunction<
            jni$_.JThrowablePtr Function(
              jni$_.Pointer<jni$_.Void>,
              jni$_.JMethodIDPtr,
            )
          >();

  /// from: `public fun stopObserving(): kotlin.Unit`
  void stopObserving() {
    _stopObserving(reference.pointer, _id_stopObserving.pointer).check();
  }
}

final class $DisplayBrightness$Type$ extends jni$_.JType<DisplayBrightness> {
  @jni$_.internal
  const $DisplayBrightness$Type$();

  @jni$_.internal
  @core$_.override
  String get signature =>
      r'Lfi/mankelisolutions/display_brightness/DisplayBrightness;';
}
