name: display_brightness_android
description: "Android implementation of the display_brightness plugin."
version: 0.1.1
homepage: https://github.com/Mankeli-Software/display_brightness
repository: https://github.com/Mankeli-Software/display_brightness/tree/main/packages/display_brightness_android

environment:
  sdk: ^3.10.0
  flutter: ">=3.3.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  display_brightness_platform_interface: ^0.1.1
  ffi: ^2.1.3
  jni: ^1.0.0
  jni_flutter: ^1.0.1
  meta: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  jnigen: ^0.16.0
  logging: ^1.3.0

flutter:
  plugin:
    implements: display_brightness
    platforms:
      android:
        dartPluginClass: DisplayBrightnessAndroid
        pluginClass: fi.mankelisolutions.display_brightness.DisplayBrightnessPlugin
        ffiPlugin: true
